### ISSUE TITLE
Unable to load YamlDotNet assembly in Powershell 7.1 host in VSCode 1.55.2

### ISSUE THREAD

**Issue by DanGough** [bitrut94/psyml#18]
Trying to use ConvertFrom-Yaml inside VSCode 1.55.2 with the Powershell 7.1 host active immediately throws this error for me:

ConvertFrom-Yaml: Could not load file or assembly 'YamlDotNet, Version=9.0.0.0, Culture=neutral, PublicKeyToken=ec19458f3c15af5e'. Could not find or load a specific file. (0x80131621)

It works fine using Powershell 5.1 in VSCode, and also works fine using Powershell 7.1 in the default shell and Windows Terminal.

**Comment by bitrut94** [comment]
Hey, @DanGough. Sadly I'm not able to reproduce this on my machine.

Could you please open a new instance of Powershell, set `$VerbosePreference = 'Continue'`, use the `ConvertFrom-Yaml` cmdlet and then paste the verbose output here?

**Comment by DanGough** [comment]
Hi, I'll close this. I did have powershell-yaml installed originally, earlier I did try completely uninstalling that from both editions of powershell, restarting etc and was still getting the error. But I just tried this again and now it's working fine! I can remove one module then import the other without any issues. If it happens again, I'll report back!

**Comment by bitrut94** [comment]
In the meantime, I'll find out what is the proper way of loading dependencies from .dll files as I might have done it wrong.
